routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
 */

Route::get('/', function () {
    //return view('welcome');
    Cookie::queue(Cookie::make('langId', 1, 3600));
    return redirect(route('login'));
});

// Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/about', 'HomeController@about')->name('about');

Route::middleware(['HasPermission'])->group(function () {
    Route::resource('applications', 'ApplicationController');
    Route::resource('attachments', 'AttachmentController');
    Route::get('/personal-info', 'ReportController@applicationsReport');
    Route::any('/report-application', 'ReportController@reportApplication')->name('report.applications');
    Route::get('report/filter', 'ReportController@filter')->name('report.filter');
    Route::get('/attached-report', 'ReportController@attachFilter')->name('attached.report');
    Route::post('/application-pdf/{id}', 'ReportController@reportApplication')->name('application.pdf');
    Route::post('/application-print/{id}', 'ReportController@reportApplication')->name('application.print');
});

// Khotian Route
Route::get('/khotian-data-entry', 'KhotianController@create');
Route::post('/khotian/store', 'KhotianController@store');
Route::get('/khotian/report/', 'KhotianController@show');
Route::post('/khotian/report/', 'KhotianController@findKhotian');
Route::any('/user-khotian-info', 'KhotianController@userKhotianInfo');

Route::get('/edit-dag-report/{id}', 'KhotianController@editDagReport');
Route::post('/store-dag-report', 'KhotianController@storeDagReport');

Route::get('/edit-owner-report/{id}', 'KhotianController@editOwnerReport');
Route::post('/store-owner-report', 'KhotianController@storeOwnerReport');

Route::get('/otp', 'OtpController@index');
Route::post('/otp-send', 'OtpController@sendOtp');
Route::post('/otp-verify', 'OtpController@verifyOtp');

Route::post('/getDivisionInfos', 'UserController@getDivisionInformation');
Route::post('/getDistrictInfos', 'UserController@getDistrictInformation')->name('getDistrictInfos');
Route::post('/getUpazliaInfo', 'UserController@getUpazliaInformation');
Route::post('/getDistrictData', 'UserController@getDistrictData');
Route::post('/getUpazilaData', 'UserController@getUpazilaData');
Route::post('/getUnionInfos', 'UserController@getUnionInformation');

Route::post('/getUpazliaInfos', 'ApplicationController@getUpazliaInformation')->name('applications.getUpazliaInfos');
// Route::post('/getUnionInfos', 'ApplicationController@getUnionInformation');
Route::post('/getPostalCode', 'ApplicationController@getPostalCodeInformation');
// Route::resource('applications', 'ApplicationController')->middleware('role:superadmin|divisionadmin|admin|editor');

// Route::resource('work-status', 'WorkStatusController');

Route::get('/application/apply', 'ApplicationController@create')->name('application.apply');
Route::post('/applications/edit', 'ApplicationController@edit');
Route::post('/applications/update', 'ApplicationController@update');

Route::get('/change-language/{id}', 'LanguageController@changeLang');
Route::post('/check-unique', 'ApplicationController@check_unique');

//Route::get('/applications-pdf', 'ReportController@applicationPdf')->name('application.pdf');
Route::post('/sp-permission', 'UserController@sp_permission_store')->name('sp_permission');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

Route::post('register-user', 'UserController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

//End Auth

//User Profile Route

Route::get('user/profile', 'UserProfileController@index')->name('user.profile');
Route::get('user/profile/edit', 'UserProfileController@edit')->name('user.profile.edit');

Route::resource('divisions', 'DivisionController');
Route::resource('districts', 'DistrictController');
Route::resource('upazilas', 'UpazilaController');
Route::resource('unions', 'UnionController');
Route::resource('bloodGroups', 'BloodGroupController');
Route::resource('genders', 'GenderController');
Route::resource('religions', 'ReligionController');
Route::resource('batchs', 'BatchController');
Route::resource('sessions', 'SessionController');
Route::resource('educationalQualifications', 'EducationalQualificationController');

Route::prefix('manage')->group(function () {
// Route::prefix('manage')->group(function () {
    Route::middleware(['HasPermission'])->group(function () {
        Route::get('/', 'ManageController@index');
        Route::get('/dashboard', 'ManageController@dashboard')->name('manage.dashboard');
        Route::resource('/users', 'UserController');
        Route::resource('/permissions', 'PermissionController', ['except' => 'destroy']);
        Route::resource('/roles', 'RoleController', ['except' => 'destroy']);
    });

});

app/BloodGroup.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BloodGroup extends Model
{
    protected $fillable = ['title_eng', 'title_bng'];
}

app/Http/Controllers/BloodGroupController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\BloodGroup;
use App\Application;
use Cookie;

class BloodGroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $getNavData = Application::getNavData();
        $langId = Cookie::get('langId');

        $BloodGroups = BloodGroup::all();

        return view('setting.blood_group.index', compact('BloodGroups', 'langId', 'getNavData'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $getNavData = Application::getNavData();
        $langId = Cookie::get('langId');

        return view('setting.blood_group.create', compact('langId', 'getNavData'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //$userId = auth()->id();
        // dd($userId);

        // $test = 1;
            $request->validate([
            'title_eng'=>'required',
            'title_bng'=>'required'
        ]);

        $BloodGroup = new BloodGroup([
            'title_eng' => $request->get('title_eng'),
            'title_bng' => $request->get('title_bng'),
            'created_by' => auth()->id()
            
        ]);

        $BloodGroup->save();
        return redirect('/bloodGroups')->with('success', 'Blood Group saved!');
    }

  
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $getNavData = Application::getNavData();
        $langId = Cookie::get('langId');

        $BloodGroup = BloodGroup::find($id);
        //dd($BloodGroup->toArray());
        return view('setting.blood_group.edit', compact('BloodGroup', 'langId', 'getNavData')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $userId = Auth::user()->id;

        $request->validate([
            'title_eng'=>'required',
            'title_bng'=>'required'
        ]);

        $BloodGroup = BloodGroup::find($id);
        $BloodGroup->title_eng =  $request->get('title_eng');
        $BloodGroup->title_bng = $request->get('title_bng');
        $BloodGroup->modified_by = $userId;
        $BloodGroup->save();

        return redirect('/bloodGroups')->with('success', 'BloodGroup updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $BloodGroup = BloodGroup::find($id);
        $BloodGroup->delete();

        return redirect('/bloodGroups')->with('success', 'Blood Group deleted!');
    }
}

resources/views/setting/blood_group/create.blade.php
@extends('layouts.app')

@section('content')

<div class="graph-section repo-filt-min">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="user-section">
                    <h3 class="user-management text-center">

                        @if($langId == 1)
                        {{"Add Blood Group"}}
                        @else($langId == 2)
                        {{"রক্তের গ্রুপ যোগ করুন"}}
                        @endif
                    </h3>
                    <hr>
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <form method="post" action="{{ route('bloodGroups.store') }}">
                        @csrf
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="title_eng">
                                    @if($langId == 1)
                                    {{"Blood Group Name (English):"}}
                                    @else($langId == 2)
                                    {{"রক্তের গ্রুপের নাম (ইংরেজী)"}}
                                    @endif
                                </label>
                                <input type="text" class="form-control" name="title_eng" />
                            </div>

                            <div class="form-group col-md-6">
                                <label for="  title_bng">
                                    @if($langId == 1)
                                    {{"Blood Group Name (Bangla):"}}
                                    @else($langId == 2)
                                    {{"রক্তের গ্রুপের নাম (বাংলা)"}}
                                    @endif
                                </label>
                                <input type="text" class="form-control" name="  title_bng" />
                            </div>

                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-outline-primary update-buttn">
                                    @if($langId == 1)
                                    {{"Add Union"}}
                                    @else($langId == 2)
                                    {{"রক্তের গ্রুপ যোগ করুন"}}
                                    @endif
                                </button>

                                <a type="submit" href="{{ url()->previous() }}" class="btn float-right btn-outline-primary back-btn">
                                    @if($langId == 1)
                                    {{"Back"}}
                                    @else($langId == 2)
                                    {{" পিছনে"}}
                                    @endif
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/setting/blood_group/edit.blade.php
@extends('layouts.app')

@section('content')


<div class="graph-section repo-filt-min">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="user-section">
                    <h3 class="user-management text-center">

                        @if($langId == 1)
                        {{"Update Blood Group"}}
                        @else($langId == 2)
                        {{"রক্তের গ্রুপ আপডেট করুন"}}
                        @endif
                    </h3>
                    <hr>
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    
                    <form method="post" action="{{ route('bloodGroups.update', $BloodGroup->id) }}">
                        @method('PATCH')
                        @csrf
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="title_eng">
                                   @if($langId == 1)
                                    {{"Blood Group Name (English):"}}
                                    @else($langId == 2)
                                    {{"রক্তের গ্রুপের নাম (ইংরেজী)"}}
                                    @endif
                                </label>

                                <input type="text" class="form-control" name="title_eng" value="{{ $BloodGroup->title_eng }}" />
                            </div>

                            <div class="form-group col-md-6">
                                <label for="  title_bng">
                                  @if($langId == 1)
                                    {{"Blood Group Name (Bangla):"}}
                                    @else($langId == 2)
                                    {{"রক্তের গ্রুপের নাম (বাংলা)"}}
                                    @endif
                                </label>
                                <input type="text" class="form-control" name="title_bng" value="{{ $BloodGroup->title_bng }}" />
                            </div>

                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-outline-primary update-buttn">
                                    @if($langId == 1)
                                    {{"Update"}}
                                    @else($langId == 2)
                                    {{"আপডেট"}}
                                    @endif
                                </button>
                                   <a type="submit" href="{{ url()->previous() }}" class="btn float-right btn-outline-primary back-btn">
                                    @if($langId == 1)
                                    {{"Back"}}
                                    @else($langId == 2)
                                    {{" পিছনে"}}
                                    @endif
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/setting/blood_group/index.blade.php
@extends('layouts.app')

@section('content')

<div class="graph-section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                @if(session()->get('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
                @endif

                <div class="user-section">
                    <div class="row">
                        <div class="col-6">
                            <h3 class="user-management">

                                @if($langId == 1)
                                {{"Blood Group"}}
                                @else($langId == 2)
                                {{"রক্তের গ্রুপ"}}
                                @endif
                            </h3>
                        </div>
                        <div class="col-6">
                            <a href="{{ route('bloodGroups.create')}}" class="creat-usrbtn float-right btn mt-0" type="button">
                              <span><i class="fas fa-plus"> </i> </span>
                                @if($langId == 1)
                                {{"New Union"}}
                                @else($langId == 2)
                                {{"নতুন রক্তের গ্রুপ"}}
                                @endif
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-12">
                <div class="user-section mt-0">
                    <table class="table table-bordered report-table table-hover">
                        <thead>
                            <tr>
                                <th class="user-thead">
                                    @if($langId == 1)
                                    {{"ID"}}
                                    @else($langId == 2)
                                    {{"আইডি"}}
                                    @endif
                                </th>
                                <th class="user-thead">
                                    @if($langId == 1)
                                    {{"Blood Group Name (English)"}}
                                    @else($langId == 2)
                                    {{"রক্তের গ্রুপের নাম (ইংরেজী)"}}
                                    @endif
                                </th>
                                <th class="user-thead">
                                    @if($langId == 1)
                                    {{"Blood Group Name (Bangla)"}}
                                    @else($langId == 2)
                                    {{"রক্তের গ্রুপের নাম (বাংলা)"}}
                                    @endif
                                </th>
                                <th class="user-thead">
                                    @if($langId == 1)
                                    {{"Actions"}}
                                    @else($langId == 2)
                                    {{"কার্যক্রম"}}
                                    @endif
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($BloodGroups as $BloodGroup)
                            <tr>
                                <td>{{$BloodGroup->id}}</td>
                                <td>{{$BloodGroup->title_eng}}</td>
                                <td>{{$BloodGroup->title_bng}}</td>
                           
                                <td>
                                    <form action="{{ route('bloodGroups.destroy', $BloodGroup->id)}}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <a href="{{ route('bloodGroups.edit', $BloodGroup->id)}}" class="btn is-light btn-outline-warning cust-usr-btn">

                                            <i class="fas fa-user-edit"></i>

                                        </a>

                                        <button class="btn is-light btn-outline-danger cust-usr-btn" type="submit">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                    </form>
                                </td>

                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


        @endsection